Fixed unreachable code
vankasteelj/opensubtitles-api pull request #46
Opened 2019-10-05 07:48 UTC by SubJunk

If `!query` is true, then `!query.path` is also true, so this is really checking for the existence of `query`

2019-10-07 07:48 UTC, vankasteelj requested changes
Hi. Thank you for your PR. You're right about the issue and the fix, but the error should still say "missing path"

2019-10-07 07:48 UTC, vankasteelj commented on index.js
> +        if (!query) throw Error('Missing query')
The error message should still be "missing path", because what is expected is a "path", the query doesn't matter

2019-10-08 20:00 UTC, SubJunk commented
Thanks for the feedback, I've corrected that now.

I am also interested in the ability to pass the info like hash and bytesize, because the machine I want to use to access the OpenSubtitles API isn't the same one that has the video files. Would you be open to me contributing that change?

2019-10-12 09:40 UTC, merged

2019-10-12 09:44 UTC, vankasteelj commented
I don't see why not, though it should not break the current version, so it should be something like: 

`identify(string) => identify({path: string})`

And the optional `identify({moviehash: string, moviebytesize: int})` is the only way to bypass "path"